<template>
  <div class="tab-content-scroll">
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p><p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p><p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p><p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p><p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p><p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p><p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p><p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p><p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p><p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p><p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p><p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p><p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
     <p>home</p>
  </div>
</template>

<script>
export default {

}
</script>
<style lang="less">
@import '../common.less';
</style>